easy_admin:
  site_name: 'Storage Rental Service'
  design:
    menu: ['Report']
  entities:
    Report:
#      class: App\Entity\Reservation
      class: App\Entity\StorageType
      list:
        title: 'List "Admin Report"'
        actions: ['-show', '-edit', '-delete', '-new']
        fields: #['title']
          - { property: 'title'}
          - { property: 'App\Repository\ReservationRepository::testrep', label: 'Custom property'}
          - { property: 'testfunc', label: 'My testfunc' }
#          - { property: 'storageTypeId' }
#          - { property: 'createdAt' }

#        dql_filter: 'entity.createdAt < '
      form:
        fields:
          - { property: 'createdAt', type: 'text' }
        entry_type: App\Form\ReportForm

    Goods:
      class: App\Entity\Goods
    GoodsProperty:
      class: App\Entity\GoodsProperty
    StorageType:
      class: App\Entity\StorageType

#        dql_filter: 'entity.'


#easy_admin:
#    entities:
#        # List the entity class name you want to manage
#        class:
#            - App\Entity\Reservation
#        - list:
#            fields: ['id']
#        - App\Entity\StorageType
#        - App\Entity\Goods
#        - App\Entity\GoodsProperty
