hwi_oauth:
    # list of names of the firewalls in which this bundle is active, this setting MUST be set
    firewall_names: [main]
#    firewall_names:        [secured_area]
    # https://github.com/hwi/HWIOAuthBundle/blob/master/Resources/doc/2-configuring_resource_owners.md
#    resource_owners:
#        aptneo_auth:
#            type:                oauth2
#            client_id:           '%oauth_client_id%'
#            client_secret:       '%oauth_client_secret%'
#            access_token_url:    '%oauth_access_token_url%'
#            authorization_url:   '%oauth_authorization_url%'
#            infos_url:           '%oauth_infos_url%'
#            scope:               '%oauth_scope%'
#            user_response_class: HWI\Bundle\OAuthBundle\OAuth\Response\PathUserResponse
#            paths:
#                identifier: 'id'
#                nickname:   'username'
#                realname:   'username'
#                email:   'email'

    resource_owners:
        facebook:
#            infos_url: 'https://graph.facebook.com/me?fields=email'
            type:                facebook
            client_id:           '%env(FB_ID)%'
            client_secret:       '%env(FB_SECRET)%'
            scope:               "email, public_profile"
            options:
                display: popup
                csrf: true
        google:
            type:                google
            client_id:           '%env(GOOGLE_ID)%'
            client_secret:       '%env(GOOGLE_SECRET)%'
            scope:               "email profile"
            options:
                access_type: offline
                display: popup
#            scope:    "https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile"
#            scope:               "https://www.googleapis.com/auth/plus.login"
#            options:
#                request_visible_actions: "http://schemas.google.com/AddActivity http://schemas.google.com/CommentActivity"
        twitter:
            type:                twitter
            client_id:           '%env(TWITTER_ID)%'
            client_secret:       '%env(TWITTER_SECRET)%'
            options:
                include_email: true